version: '3.2'

services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sec_service
    ports:
    - 5432:5432
